### ISSUE TITLE
nivo slider formatting issues when attachment titles contain HTML tags

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-nivo-slider#3]
Raised in the support forum.
See https://wordpress.org/support/topic/1141-hiding-everything-but-the-image-on-subsequent-slides

Anton42 proposed a fix using preg_replace() instead of str_replace()

Note: I have yet to reproduce the problem as raised. I have found another issue.

**Comment by bobbingwide** [comment]
The other issue, which produces a similar problem is cause by passing the `$alt` variable to retimage() instead of a null value for the `$width` parameter. 
Until other evidence is provided I'll assume this is the problem that was reported.

**Comment by NPC** [comment]
Hi, thank you, this solved the problem that I reported.
